const RESULT = {
    SAVE: 'RESULT_SAVE'
};

const USER_INTERACTION = {
    UPDATE : 'UPDATE_USER_INTERACTION'
};

const SLOT_RUNNING_STATUS = {
    STATUS : 'SLOT_RUNNING_STATUS'
};

export { RESULT,USER_INTERACTION,SLOT_RUNNING_STATUS };